
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Domain.Models
{

using System;
    using System.Collections.Generic;
    
public partial class vatsetting
{

    public long VATID { get; set; }

    public double VatPercent { get; set; }

    public Nullable<short> PricesWithVAT { get; set; }

    public Nullable<short> ISVAT { get; set; }

    public Nullable<short> ISDiscforpro { get; set; }

    public Nullable<short> ISDiscafterpro { get; set; }

}

}
